version: '2'
services:
  dockerdj:
    image: openidentityplatform/opendj:latest
    container_name: ldap
    environment:
      ROOT_USER_DN: "cn=everex"
      ROOT_PASSWORD: "everex"
      BASE_DN: "dc=everex,dc=kr"
    ports:
      - "389:1389"
      - "636:1636"
      - "4444:4444"
    volumes:
      - "./opendj/logs:/opt/opendj/data/logs"
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "7080:80"
    volumes:
      - "./file:/usr/share/nginx/html:ro"
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
